### ISSUE TITLE
Empty vdir not working with reverse proxy

### ISSUE THREAD

**Issue by Czechball** [sameerdhoot/wolweb#10]
Hello.
I'm trying to use wolweb with a reverse proxy (Caddy). When I leave the default "/wolweb" vdir and create this Caddy directive:
```
127.0.0.1:80 {
	reverse_proxy 127.0.0.1:8088
}
```
I can access wolweb at localhost:80/wolweb, as intended. But I'd like to ommit the /wolweb part, so I changed "vdir" in wolweb's config to just "/", and now when I try to visit localhost:80, I get too many redirects.

**Comment by rdgerken** [comment]
Can anyone confirm this merge fixes this problem? I'm trying this behind Traefik 2, using "/" for the vdir environment variable - and I can't get it to work through the proxy using a subdomain with no path (502 error). Hitting it locally with http://<localip>:8089 with no path works fine.

**Comment by abelgomez** [comment]
I tried the latest code at https://github.com/sameerdhoot/wolweb/commit/92bd05d0541b308b0d06c64d808c5826d938e75f, and the "/" vdir does not work for me (I still enter in a loop of 302 redirects) when getting `http://mysite:8089` (for obvious reasons, I didn't even try my reverse proxy serving on https).

**Comment by abelgomez** [comment]
Ooops, my mistake, I didn't properly refresh my environment.

I confirm that the latest code in https://github.com/sameerdhoot/wolweb/commit/92bd05d0541b308b0d06c64d808c5826d938e75f indeed does work, both directly from the `wolweb` serving on 8089, and through an nginx proxy listening on 443.

I had to thoroughly clean cached stuff in my web browser.

**Comment by rdgerken** [comment]
Thank you for confirming. I'll keep trying with Traefik.

**Comment by sameerdhoot** [comment]
@rdgerken I hope you are able to find a working solution. I am closing this issue since it is user environment/config issue.
