### ISSUE TITLE
[Improvement] Allow editing of broadcast IP when creating a device

### ISSUE THREAD

**Issue by huornlmj** [sameerdhoot/wolweb#14]
When I create a device in the web UI, the broadcast IP field is disabled and defaults to 192.168.1.255.  As a user I would like to be able to enter an IP address of my choice when creating the device.  The only option I currently have is to accept the default IP address, hit SAVE  and then re-edit my new device which allows me access to the broadcast IP address field.

**Comment by sameerdhoot** [comment]
@huornlmj I have edited the code and now you can control the broadcast IP.
