### ISSUE TITLE
404 page not found after building project

### ISSUE THREAD

**Issue by wesros11** [sameerdhoot/wolweb#17]
Hello,

Im getting the 404 page not found error after building the project on a windows machine.

I've tried a lot but cant make the project to work.

Just "go build -o wol.exe" is not enough. Had to install a bunch more.

am i doing something wrong?

**Comment by sameerdhoot** [comment]
I have tested windows build again and seems to build and run fine. It could be an issue with your build config or environment. I now have a docker container for Windows published under packages... check them out.
