### ISSUE TITLE
Cannot build docker image

### ISSUE THREAD

**Issue by karafso** [sameerdhoot/wolweb#2]
When running `docker build -t wolweb .` I get the following error:

```
Step 6/16 : RUN go build -o wolweb .
 ---> Running in 83bad7fbe7ac
go: cannot find main module, but found .git/config in /wolweb
	to create a module there, run:
	go mod init
```

I've created a PR that resolves this for me by adding the suggested command to the Dockerfile

**Comment by max-frei** [comment]
I also had this issue and adding the init command to the Dockerfile fixed it. Kudos for your PR.

**Comment by sameerdhoot** [comment]
Merged the pull request.
