### ISSUE TITLE
Little Idea

### ISSUE THREAD

**Issue by nebukadhezer** [sameerdhoot/wolweb#21]
First off thanks for this! 
Cool little timesaver.

I am not much into go at all but I was wondering if it would be easily doable to extend the machines, with a simple timer.
So one can specify in the json file a boot up time per machine (sure this is just a guess)
Once wakeup has been hit the timer counts down... maybe it can even play a sound ...
I am having windows machines and I sometimes just miss them as they go to sleep again.
If this is not matching your idea of the tool just ignore my proposition :-)

**Comment by sameerdhoot** [comment]
It is a good idea but unfortunately, I don't have the bandwidth to do this now. I am willing to merge a PR if you are able to put together a working solution.

**Comment by sameerdhoot** [comment]
Actually, this can be done using cron job in Linux or as PowerShell script in windows running in task scheduler. All you have to do is send a web request at a scheduled time. On linux using curl and in windows use Invoke-WebRequest.

I highly suggest that you have a docker container running [crontab-ui ](https://github.com/alseambusher/crontab-ui)

I dont think it is useful to have a timer funtion here to keep things simple.
