### ISSUE TITLE
Debian_Dockerfile missing go mod init wolweb line

### ISSUE THREAD

**Issue by misosoup7** [sameerdhoot/wolweb#22]
Debian Dockerfile fails because go mod init wolweb is missing compared to the Alpine Dockerfile. Should be the following (I also updated it to Bullseye over buster since I was running Bullseye Debian.

```# docker build -t wolweb .
FROM golang:bullseye AS builder

LABEL org.label-schema.vcs-url="https://github.com/sameerdhoot/wolweb" \
      org.label-schema.url="https://github.com/sameerdhoot/wolweb/blob/master/README.md"

RUN mkdir /wolweb
WORKDIR /wolweb

# Install Dependecies
RUN git clone https://github.com/sameerdhoot/wolweb . && \
    go mod init wolweb && \
    go get -d github.com/gorilla/handlers && \
    go get -d github.com/gorilla/mux && \
    go get -d github.com/ilyakaznacheev/cleanenv

# Build Source Files
RUN go build -o wolweb .

# Create 2nd Stage final image
FROM debian
WORKDIR /wolweb
COPY --from=builder /wolweb/index.html .
COPY --from=builder /wolweb/wolweb .
COPY --from=builder /wolweb/devices.json .
COPY --from=builder /wolweb/config.json .
COPY --from=builder /wolweb/static ./static

ARG WOLWEBPORT=8089

CMD ["/wolweb/wolweb"]

EXPOSE ${WOLWEBPORT}
```

**Comment by sameerdhoot** [comment]
The repo now has a new Dockerfile which uses Go version 1.20. This was suggested by another PR which I have now merged. I am working on another PR which updates the Debain_Dockerfile and I will soon merge the PR. I am waiting for the PR author to make some changes before the merge.

**Comment by sameerdhoot** [comment]
I have checked in a new [Debian_Dockerfile](https://github.com/sameerdhoot/wolweb/blob/main/Debian_Dockerfile) which now uses Go 1.20
