### ISSUE TITLE
Web interface does not render properly in Firefox

### ISSUE THREAD

**Issue by ohmstance** [sameerdhoot/wolweb#26]
I am glad there is WoL with a web interface. However, the web interface does not render properly when viewed through Firefox. The navbar is missing dark background and the text "GET" is offset up from the center of the pill. See the following images:

### Firefox 115.0.2
![Mozilla Firefox](https://github.com/sameerdhoot/wolweb/assets/58171737/58b573d8-33be-4d2b-a325-0e608740af27)

### MS Edge 115.0.1901.183
![Microsoft Edge](https://github.com/sameerdhoot/wolweb/assets/58171737/ab28f805-4a4c-401c-a54e-226c40b87b11)

**Comment by ohmstance** [comment]
Firefox does not support CSS nesting, which is used in styles.css. I'll make a PR.

**Comment by sameerdhoot** [comment]
@ohmstance Thank you looking into this. I will merge the PR when you make it available.

**Comment by ohmstance** [comment]
I've submitted a PR. It includes some optimization for small screens.

**Comment by sameerdhoot** [comment]
Merged #27
