### ISSUE TITLE
Mark a machine as "Send on Launch"

### ISSUE THREAD

**Issue by martini1992** [sameerdhoot/wolweb#31]
Hi, Adding the ability to mark one of the WoL entires for a machine as "Send on Launch" where the wake packet will be automatically sent when the application starts, posiibly even with a "Delay" feature so we could start machines in a specific order automatically once the first machine starts.

My only reservation would be having a way to override the auto-send if you don't want to send it a particular time.

**Comment by sameerdhoot** [comment]
This is not something IMO will add value. This is a webapp which is running 24x7 and it should be launched once and then keep running as a service. Now to achieve what you want you can schedule a job somewhere to send API calls to this webapp to wake the machine.... wait for them to boot and then send request to another machine after first one has completely booted. Think of a shell script which can be scheduled using cron job.

**Comment by martini1992** [comment]
Ok, my plan was to host this on storage server and then use it to boot satellite application servers that use the network storage, to ensure the storage is ready before the others try to boot.

**Comment by sameerdhoot** [comment]
I get your point but this is just providing the service to send the magic packet and primary use case was to make it accessible from outside with reverse proxy. When in the local environment you can still use this webapp but then there are plenty of other options available to send the magic packet from the console. You can use those console utilities with the cron job scheduling to trigger sending magic packets to other satellite applications (devices) from your storage server.

**Comment by martini1992** [comment]
Fair enough, I just liked the UI and thought it'd come in useful after a power outage.

**Comment by sameerdhoot** [comment]
Glad you liked the UI. Unfortunately, in your case I will have to redirect you to using something else. Also, the UI is because of all the users who have contributed to this repo. I did not do it alone.
