### ISSUE TITLE
Able to run without docker?

### ISSUE THREAD

**Issue by nahventure** [sameerdhoot/wolweb#32]
Trying to see if I can run it directly on apache2, I have a 1gb pi3 so resources are limited.

I uploaded the files to the server and it errors with the following;:

Error
Unable to retrieve device data!

**Comment by sameerdhoot** [comment]
@nahventure make sure that it can access devices.json file which should be in same folder as the executable. I have ran this before on my router and it can run independently without a docker container.

**Comment by nuclear-banana** [comment]
@sameerdhoot i am also curious and have the same issue - please help me out here, where to place the devices.json file exactly?

**Comment by ellisdickinson46** [comment]
@nuclear-banana from what I can tell, the files are pulled from the consoles current working directory. Therefore, you would have to be executing from within the folder where the binary is located for the program to find them instead of the files being in a particular location.

**Comment by ellisdickinson46** [comment]
#36 would help in scenarios, would you be able to test with the changes made in my fork on main and let me know if that solves this issue.

**Comment by ellisdickinson46** [comment]
Closing in favour of #35, can be resolved with config file parameterisation.
