### ISSUE TITLE
Web interface hardcodes "/wolweb/wake" irrespective of vdir specified

### ISSUE THREAD

**Issue by palves** [sameerdhoot/wolweb#38]
Even if you specify a diffent vdir than the "/wolweb" default, like e.g., in a docker compose:

  WOLWEBVDIR: "/"

The web interface will still tell you to use the "/wolweb/wake/" URLs, which of course won't work:

 "Wake-up directly using HTTP Requests
 /wolweb/wake/<Device Name> - Returns a JSON object"

**Comment by sameerdhoot** [comment]
@ellisdickinson46 has submitted a PR which is now merged and should resolve the issue.
