### ISSUE TITLE
404 not found when deploying with Portainer

### ISSUE THREAD

**Issue by stephendt** [sameerdhoot/wolweb#9]
Howdy folks. I am a bit of a newb to Docker, so go easy. I just tried to add WolWeb to my docker host using Portainer, and the best I can accomplish is a "404 not found" error page: https://i.imgur.com/LMH7OJ2.jpeg

I added this docker container (https://hub.docker.com/r/aranajuan/wolweb), configured host networking under advanced container settings, and even after manually fiddling and setting up environment variables (yes I also tried changing the port), I'm getting a 404 not found error. It seems like something is messing up pathing? I'm sure this is something dumb. Some guidance would be greatly appreciated.

A few extra screenshots: 

https://i.imgur.com/8IiUdbj.jpeg
https://i.imgur.com/G4amCY9.jpeg
https://i.imgur.com/ePGyC8G.jpeg

**Comment by sameerdhoot** [comment]
@stephendt please use the build instructions provided on [project page](https://github.com/sameerdhoot/wolweb).

The image which you are trying to use might use a different platform/architecture than what you are using.

**Comment by sameerdhoot** [comment]
@stephendt sorry. I just noticed that in the screenshot which you provided you are trying to open http://192.168.20.50:8075

This will generate a 404 error and is expected. The application is hosted under a virtual director path **/wolweb** so, can you please try to open URL http://192.168.20.50:8075/wolweb?

This virtual directory can be configured by passing environment variable in Portainer UI called **WOLWEBDIR**
